### PR TITLE
fix: inherent error, mocks, timestamp critical

### LINKED ISSUE #286: fix `InherentError` type
* `InherentErrorApplication` is missing an additional argument. Reference [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/primitives/inherents/src/lib.rs#L182).
* `InherentErrorDecodingFailed` is missing one additional parameter - the actual error.
* `NewInherentErrorFatalErrorReported` is called when decoding fails. `NewInherentErrorDecodingFailed` should be called instead. Usages - [here](https://github.com/LimeChain/gosemble/blob/develop/frame/timestamp/module.go#L128) and [here](https://github.com/LimeChain/gosemble/blob/develop/frame/timestamp/module.go#L133).

### PR DESCRIPTION
**Pull request by failfmi**
**Detailed description**:
* fix storage value mock funcs
* fix inherent error inherent identifier to be fixed sequence
* fix timestamp flow
* add tests

**Which issue(s) this PR fixes**:
Fixes #286 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: frame/timestamp/module.go [hunk 1]
```diff
@@ -86,16 +87,15 @@ func (m Module) CreateInherent(inherent primitives.InherentData) (sc.Option[prim
 		log.Critical(errTimestampInherentNotProvided)
 	}
 
-	buffer := &bytes.Buffer{}
-	buffer.Write(sc.SequenceU8ToBytes(inherentData))
+	buffer := bytes.NewBuffer(sc.SequenceU8ToBytes(inherentData))
 	ts, err := sc.DecodeU64(buffer)
 	if err != nil {
-		return sc.Option[primitives.Call]{}, err
+		log.Critical(errTimestampInherentDataNotCorrectlyEncoded)
```
Comment (tgntr) [inline frame/timestamp/module.go]: is this based on a convention for panic logging vs returning errors? there is the opposite change in a recent [PR](https://github.com/LimeChain/gosemble/pull/284/files#diff-cabe204e1a3660f7878ee5fef41f99fcfc9afd175d70dab9fbde0aab24dff1fbL216-R222)

as we already started addressing logger dependency decoupling in https://github.com/LimeChain/gosemble/issues/262 as a next step we could consider injecting the logger at the top level (probably api modules) and handling errors in a single layer  for consistency.

Comment (failfmi) [reply frame/timestamp/module.go]: Let's see how it goes with top-level handling. Fixed `CreateInherent` and left TODOs for `CheckInherent` to be taken into account when refactoring the errors.

**Review by tgntr — APPROVED** [review]

**Review by radkomih — APPROVED** [review]
